src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $passwordResetToken;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastnamePrefix;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $phonenumber;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type(
     *    type="File",
     *    message="The value {{ value }} is not a valid {{ type }}.")
     * @Assert\Image()
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $registrationIp;

    public function __construct()
    {
        $this->password = '';
        $this->avatar = '';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPasswordResetToken(): ?string
    {
        return $this->passwordResetToken;
    }

    public function setPasswordResetToken(?string $passwordResetToken): self
    {
        $this->passwordResetToken = $passwordResetToken;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getLastnamePrefix(): ?string
    {
        return $this->lastnamePrefix;
    }

    public function setLastnamePrefix(string $lastnamePrefix): self
    {
        $this->lastnamePrefix = $lastnamePrefix;

        return $this;
    }

    public function getPhonenumber(): ?string
    {
        return $this->phonenumber;
    }

    public function setPhonenumber(string $phonenumber): self
    {
        $this->phonenumber = $phonenumber;

        return $this;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getAvatar()
    {
        return $this->avatar;
    }

    public function getAvatarUri()
    {
        return $_ENV['AVATAR_UPLOAD_DIR'].$this->avatar;
    }

    public function setAvatar($avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getRegistrationIp(): ?string
    {
        return $this->registrationIp;
    }

    public function setRegistrationIp(string $registrationIp): self
    {
        $this->registrationIp = $registrationIp;

        return $this;
    }
}

templates/security/forgot-password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wachtwoord herstellen{% endblock %}

{% block body %}
    <div id="mainContent" class="pageWidth">
        <h1>Wachtwoord vergeten</h1>
        <p>Je wachtwoord vergeten? No worries, kan iedereen gebeuren. Vul je e-mailadres hieronder en we sturen je een link om je wachtwoord te resetten.</p>

        {% if message %}<p class="alert neutral">{{ message }}</p>{% endif %}
        <form method="post">
           <div>
                <label>Email</label>
                <input type="email" name="email" placeholder="Email" required autofocus>
            </div>
            <button type="submit" class="safe">Verstuur</button>
        </form>
    </div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
    <form method="post" id="LoginWrap">

        <h1>Login</h1>
        {% if error %}
            <div class="alert careful">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        <div>
            <label>E-mail</label>
            <input type="email" value="{{ last_username }}" name="email" placeholder="E-mail" required autofocus>
        </div>
        <div>
            <label>Wachtwoord</label>
            <input type="password" name="password" placeholder="Wachtwoord" required>
        </div>

        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >

        <button class="safe" type="submit">
            Login
        </button>

        <p id="forgotPasswordWrap">
            <small><a href="{{ path('app_register') }}">Registreren?</a></small><br />
            <small><a href="{{ path('app_forgot_password') }}">Wachtwoord vergeten?</a></small>
        </p>
    </form>
{% endblock %}

templates/security/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profiel {{ user.firstname }}{% endblock %}

{% block body %}
    <div id="mainContent" class="pageWidth">
        <h1>Profiel</h1>
        <p>Hallo <strong>{{ user.firstname }}</strong>! Gefeliciteerd, je hebt het gered. Hieronder de ingevulde gegevens:</p>

        <table>
            <tr>
                <th width="100">Naam</th>
                <td>{{ user.firstname }} {{ user.lastnamePrefix }} {{ user.lastname }}</td>
                <td rowspan="10"><img style="max-width: 100px;" src="{{ user.avatarUri }}" /></td>
            </tr>
            <tr>
                <th>Schermnaam</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Telefoon</th>
                <td>{{ user.phonenumber }}</td>
            </tr>
            <tr>
                <th>IP-adres</th>
                <td>{{ user.registrationIp }}</td>
            </tr>
            <tr>
                <th>E-mailadres</th>
                <td>{{ user.email }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

templates/security/reset-password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wachtwoord herstellen{% endblock %}

{% block body %}
    <div id="mainContent" class="pageWidth">
        <h1>Wachtwoord aanpassen</h1>
        <p>Als je hieronder een nieuw wachtwoord* invuld, kun je weer inloggen!</p>

        {% if message %}<p class="notice">{{ message }}</p>{% endif %}
        {% if user %}
        <form method="post">
           <div>
                <label>Nieuw wachtwoord</label>
                <input type="password" name="password" placeholder="Je wachtwoord (min. {{ passwordMinLength }} tekens)" minlength="{{ passwordMinLength }}" required autofocus>
            </div>
           <div>
                <label>Verifieer wachtwoord</label>
                <input type="password" name="password_verify" placeholder="Nogmaals je wachtwoord" required>
            </div>
            <button type="submit" class="safe">Verstuur</button>
        </form>

        <p></p>

        <p>
            <small>
            <em>* Moeite met een goed wachtwoord verzinnen? Met deze truc maak je een goed wachtwoord:<br />

                &nbsp;&nbsp;- Lengte is belangrijker dan gek gedoe; Verzin 4 willekeurige woorden en plak er een speciaal teken tussen:<br/>
                &nbsp;&nbsp;&nbsp;&nbsp;<strong>{{ examplePassword }}</strong>. Makkelijk onthouden, maar wel lang, hoofd-&amp;kleine letters en speciale tekens.
            </em>
            </small>
        </p>
        {% else %}
        <p>We hebben geen account gevonden. Mogelijk is het fout overgenomen, is deze link al een keer gebruikt.</p>
        {% endif %}
    </div>
{% endblock %}